# Generated by Django 5.2.4 on 2025-07-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('cutout_image', models.URLField()),
                ('model_image', models.URLField()),
                ('currency', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('stock_total', models.IntegerField()),
                ('is_customizable', models.BooleanField()),
                ('discount_label', models.CharField(blank=True, max_length=100, null=True)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('short_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
