# Generated by Django 5.2.4 on 2025-07-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('available_sizes', models.TextField(blank=True, null=True)),
                ('brand_id', models.BigIntegerField(blank=True, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('has_similar', models.BooleanField(default=False)),
                ('cutout_image', models.URLField(blank=True, null=True)),
                ('model_image', models.URLField(blank=True, null=True)),
                ('is_customizable', models.BooleanField(default=False)),
                ('merchandiser_category', models.CharField(blank=True, max_length=100, null=True)),
                ('merchandiser_season', models.CharField(blank=True, max_length=50, null=True)),
                ('merchandiser_year', models.CharField(blank=True, max_length=10, null=True)),
                ('merchant_id', models.BigIntegerField(blank=True, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('full_price', models.FloatField(blank=True, null=True)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('discount_label', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('stock_total', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
