# Generated by Django 5.2.4 on 2025-07-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='full_price',
            new_name='final_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='intital_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='merchandiser_category',
            new_name='merchandise_label',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='merchandiser_season',
            new_name='merchandise_labelfield',
        ),
        migrations.RemoveField(
            model_name='product',
            name='merchandiser_year',
        ),
        migrations.RemoveField(
            model_name='product',
            name='merchant_name',
        ),
    ]
