# Generated by Django 5.2.4 on 2025-07-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_full_price_product_final_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='intital_price',
            new_name='initial_price',
        ),
    ]
