# Generated by Django 5.2.4 on 2025-07-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_intital_price_product_initial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='formatted_final_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='formatted_initial_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
