# Generated by Django 5.2.5 on 2025-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_formatted_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
