# Generated by Django 5.2.4 on 2025-08-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
